gazebo_ros_control/pid_gains:
  front_left_wheel:  {p: 500.0, i: 0.0, d: 1.0}
  front_right_wheel: {p: 500.0, i: 0.0, d: 1.0}
  rear_left_wheel:   {p: 500.0, i: 0.0, d: 1.0}
  rear_right_wheel:  {p: 500.0, i: 0.0, d: 1.0}